[store]
dir = "target/nextest"

[profile.default]
slow-timeout = { period = "60s" }
failure-output = "immediate-final"
retries = { backoff = "exponential", count = 2, delay = "1s", jitter = true, max-delay = "10s" }
fail-fast = false

[profile.default.junit]
path = "junit.xml"
report-name = "nextest-run"

store-success-output = true
store-failure-output = true
