[store]
dir = "target/nextest"

[profile.default]
slow-timeout = { period = "60s" }

[profile.default.junit]
path = "junit.xml"
report-name = "nextest-run"

store-success-output = true
store-failure-output = true
