name: CI

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-test-artifacts:
    name: Build Test Artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2.2.1
        with:
          shared-key: "test-artifacts"
          save-if: ${{ github.ref == 'refs/heads/master' }}

      - name: Install nextest
        uses: taiki-e/install-action@nextest

      - name: Build test artifacts
        run: cargo nextest archive --release --archive-file nextest-archive.tar.zst

      - name: Upload archive to workflow
        uses: actions/upload-artifact@v3
        with:
          name: nextest-archive
          path: nextest-archive.tar.zst
          retention-days: 2

  run-tests:
    name: Run tests with partitioning
    runs-on: ubuntu-latest
    needs: build-test-artifacts
    strategy:
      matrix:
        partition: [ 1, 2 ]
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Install nextest
        uses: taiki-e/install-action@nextest
      - name: Download archive
        uses: actions/download-artifact@v3
        with:
          name: nextest-archive
      - name: Copy example.env to .env
        run: cp example.env .env
      - name: Run tests
        run: |
          ~/.cargo/bin/cargo-nextest nextest run --archive-file nextest-archive.tar.zst \
            --partition count:${{ matrix.partition }}/2

      - name: Upload Test Reports
        uses: actions/upload-artifact@v3
        with:
          name: report-${{ matrix.partition }}
          path: target/nextest/default/*
