name: TEST

on:
  workflow_dispatch:
    inputs:
      run_generate_report:
        description: 'Whether to run the Generate Report step'
        required: false
        default: 'true'

env:
  CARGO_TERM_COLOR: always

jobs:
  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: "true"
          cache-all-crates: "true"
          shared-key: "test-artifacts"
          save-if: ${{ github.ref == 'refs/heads/master' }}

      - name: Install nextest
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-nextest

      - name: Copy example.env to .env
        run: cp example.env .env

      - name: Run tests
        run: cargo nextest run --release

      - name: Upload Test Reports
        uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: report
          path: nextest/default

  generate-report:
    name: Generate and Upload Test Report
    runs-on: ubuntu-latest
    needs: run-tests
    if: ${{ github.event.inputs.run_generate_report != 'false' || github.event.inputs.run_generate_report != '0' }}
    steps:
      - name: Download Test Reports
        uses: actions/download-artifact@v3
        with:
          name: report
          path: reports/report

      - name: Merge Test Reports
        run: |
          mkdir -p reports/all
          cp reports/report/*.xml reports/all/

      - name: Generate Report
        id: xunit-viewer
        uses: AutoModality/action-xunit-viewer@v1
        with:
          results: reports

      - name: Upload Test Report
        uses: actions/upload-artifact@v3
        with:
          name: html-report
          path: reports/index.html